services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: customer-return-api:local
    container_name: api
    ports:
      - "8000:8000"
    
    # 1. SỬA LẠI THƯ MỤC LÀM VIỆC GỐC: Đưa thẳng về /app
    working_dir: /app
    
    # 2. SỬA LẠI VOLUMES: Mount thư mục hiện tại vào đúng gốc /app
    volumes:
      - .:/app
      
    environment:
      - PYTHONPATH=.                                
      - MLFLOW_TRACKING_URI=http://host.docker.internal:5000
      - MLFLOW_MODEL_URI=models:/customer-return-champion@champion
      - PYTHONUNBUFFERED=1
      
    # 3. Giữ nguyên lệnh uvicorn này, nó sẽ quét thư mục api nằm trực tiếp trong /app
    command: uvicorn api.app:app --host 0.0.0.0 --port 8000